language: node_js
node_js:
- "6"
branches:
  only:
  - post
env:
  global:
    secure: lgJDP6O43fxGkjYrZlw7P4X96ax0luPx9wiQk1rKHBvGTrO/tsn3I7SRhdjKFdU98ZMawxUmWqWUB5ICARlUy+eNyIt86hXFsZ+8diuphJW07paZ/dz0epvxEuRsxcygLmAKIpOikpFMTI14COhFYdGbgdLSmY3RQygFMEyeR03HvTvj8sA3hRN1lde9REKoZK1U7JvEuqJ/lY7aQsxzLrezjxrAGBXoMdfqfVz2aPQ0ElUBtIbAXJqsrYZx5pIfAL9ve3tmdGuaJatHHDkCJSIQZRyjG/Qjl9ee3Oo+hHN/9MpaVtiPfefK1hhX/M5YOBvhQ7+4ax6HUgo6HexfezHAy3v29tsOwLhKHfRnwMrs53o4PPOA5jCaoovbLXIdxu2ICX4X9cdjWk8jXONSiEkD45DFv5Z0lGHbYs2qChoCxbeSCU8vKAnQpMC6yyqye0FkPFKZyjvOfmFrfHl+gJ1RJZ6XsvedJRkUiyVaSzFpD0Br6Jq/s4Ilsc7ZJ8M2yrukfp9lDhFuxDC8naVLWwTCLNBpiRmYronq28hEN/SvRk1CneMg8Y0RsE9aL1Ae3IHelDJP4cEZnBszGPW5oZo4YMxDMGbEXJmU0KNxEnJ2wIJWeh9wPYhnSXsYmZwTVlMrtsUBx6i2IwO/YDLo9UreRJpCd7KD4tDcqmlYbfk=

before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "S1T49"
- git config --global user.email CS1T49@163.com
- sed -i'' "s~https://github.com/S1T49/s1t49.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/S1T49/s1t49.github.io.git~" _config.yml
install:
- npm install
script:
- hexo clean
- hexo d -g
