language: node_js
node_js:
- '6'
branches:
  only:
  - post
before_install:
- openssl aes-256-cbc -K $encrypted_8005450f0483_key -iv $encrypted_8005450f0483_iv
  -in .travis/id_rsa_s1t49.enc -out ~/.ssh/id_rsa -d
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install hexo-deployer-git --save
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config  ~/.ssh/config
- git config --global user.name "S1T49"
- git config --global user.email CS1T49@163.com
install:
- npm install
script:
- hexo clean
- hexo d -g
